### ISSUE TITLE
Grammar and Sentiment BERT models are not available

### ISSUE THREAD

**Issue by abhinavdayal** [farazkhanfk7/textly-drf-api#1]
https://drive.google.com/uc?export=download&id=1bfFRMEnWywP_1jW-5z66FO9iVUfGoh6t

and

https://drive.google.com/uc?export=download&id=1LuGfTU18W99TA6XFb3g99kyIDRWw_kIr

as configured in load_models.sh, both links are not valid anymore. These need to be updated.

**Comment by farazkhanfk7** [comment]
Yes, the files for trained models were deleted on Google Drive. Will update the links soon. Thanks
